version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./data/init.sql:/data/application/init.sql
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql        
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ra_collector
    ports:
      - "3306:3306"
    networks:
      - ra-network
  ra-api:
    image: darlankenobi/ra-api-backend
    build: ../ra-dash-backend/
    container_name: ra-api-backend 
    environment:
      RA_API_DB_NAME: ra_collector
      RA_API_DB_USER: root
      RA_API_DB_PASS: root
      RA_API_DB_HOST: db
      RA_API_PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - ra-network
    depends_on:
      - db
networks:
  ra-network:
    name: ra-network
    driver: bridge
